//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTarjetas.ServicioTarjetas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMISOR", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioTarjetas.Modelo")]
    [System.SerializableAttribute()]
    public partial class EMISOR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EMI_CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMI_DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EMI_NUMERO_DIGITOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMI_PREFIJOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_CODIGO {
            get {
                return this.EMI_CODIGOField;
            }
            set {
                if ((this.EMI_CODIGOField.Equals(value) != true)) {
                    this.EMI_CODIGOField = value;
                    this.RaisePropertyChanged("EMI_CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_DESCRIPCION {
            get {
                return this.EMI_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMI_DESCRIPCIONField, value) != true)) {
                    this.EMI_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("EMI_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_NUMERO_DIGITOS {
            get {
                return this.EMI_NUMERO_DIGITOSField;
            }
            set {
                if ((this.EMI_NUMERO_DIGITOSField.Equals(value) != true)) {
                    this.EMI_NUMERO_DIGITOSField = value;
                    this.RaisePropertyChanged("EMI_NUMERO_DIGITOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_PREFIJO {
            get {
                return this.EMI_PREFIJOField;
            }
            set {
                if ((object.ReferenceEquals(this.EMI_PREFIJOField, value) != true)) {
                    this.EMI_PREFIJOField = value;
                    this.RaisePropertyChanged("EMI_PREFIJO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TARJETA", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioTarjetas.Modelo")]
    [System.SerializableAttribute()]
    public partial class TARJETA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAR_CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAR_CODIGO_CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAR_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TAR_FECHA_EMISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TAR_FECHA_VENCIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAR_NOMBRE_CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAR_NUMEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TAR_SALDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAR_TIPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAR_CODIGO {
            get {
                return this.TAR_CODIGOField;
            }
            set {
                if ((this.TAR_CODIGOField.Equals(value) != true)) {
                    this.TAR_CODIGOField = value;
                    this.RaisePropertyChanged("TAR_CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAR_CODIGO_CLIENTE {
            get {
                return this.TAR_CODIGO_CLIENTEField;
            }
            set {
                if ((this.TAR_CODIGO_CLIENTEField.Equals(value) != true)) {
                    this.TAR_CODIGO_CLIENTEField = value;
                    this.RaisePropertyChanged("TAR_CODIGO_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAR_ESTADO {
            get {
                return this.TAR_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.TAR_ESTADOField, value) != true)) {
                    this.TAR_ESTADOField = value;
                    this.RaisePropertyChanged("TAR_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TAR_FECHA_EMISION {
            get {
                return this.TAR_FECHA_EMISIONField;
            }
            set {
                if ((this.TAR_FECHA_EMISIONField.Equals(value) != true)) {
                    this.TAR_FECHA_EMISIONField = value;
                    this.RaisePropertyChanged("TAR_FECHA_EMISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TAR_FECHA_VENCIMIENTO {
            get {
                return this.TAR_FECHA_VENCIMIENTOField;
            }
            set {
                if ((this.TAR_FECHA_VENCIMIENTOField.Equals(value) != true)) {
                    this.TAR_FECHA_VENCIMIENTOField = value;
                    this.RaisePropertyChanged("TAR_FECHA_VENCIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAR_NOMBRE_CLIENTE {
            get {
                return this.TAR_NOMBRE_CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TAR_NOMBRE_CLIENTEField, value) != true)) {
                    this.TAR_NOMBRE_CLIENTEField = value;
                    this.RaisePropertyChanged("TAR_NOMBRE_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAR_NUMERO {
            get {
                return this.TAR_NUMEROField;
            }
            set {
                if ((object.ReferenceEquals(this.TAR_NUMEROField, value) != true)) {
                    this.TAR_NUMEROField = value;
                    this.RaisePropertyChanged("TAR_NUMERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TAR_SALDO {
            get {
                return this.TAR_SALDOField;
            }
            set {
                if ((this.TAR_SALDOField.Equals(value) != true)) {
                    this.TAR_SALDOField = value;
                    this.RaisePropertyChanged("TAR_SALDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAR_TIPO {
            get {
                return this.TAR_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TAR_TIPOField, value) != true)) {
                    this.TAR_TIPOField = value;
                    this.RaisePropertyChanged("TAR_TIPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioTarjetas")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTarjetas.IEmisor")]
    public interface IEmisor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetData", ReplyAction="http://tempuri.org/IEmisor/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetData", ReplyAction="http://tempuri.org/IEmisor/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ConsultarEmisor", ReplyAction="http://tempuri.org/IEmisor/ConsultarEmisorResponse")]
        AplicacionTarjetas.ServicioTarjetas.EMISOR[] ConsultarEmisor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ConsultarEmisor", ReplyAction="http://tempuri.org/IEmisor/ConsultarEmisorResponse")]
        System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.EMISOR[]> ConsultarEmisorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ObtenerEmisorTarjeta", ReplyAction="http://tempuri.org/IEmisor/ObtenerEmisorTarjetaResponse")]
        string ObtenerEmisorTarjeta(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ObtenerEmisorTarjeta", ReplyAction="http://tempuri.org/IEmisor/ObtenerEmisorTarjetaResponse")]
        System.Threading.Tasks.Task<string> ObtenerEmisorTarjetaAsync(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ObtenerInformacionTarjeta", ReplyAction="http://tempuri.org/IEmisor/ObtenerInformacionTarjetaResponse")]
        AplicacionTarjetas.ServicioTarjetas.TARJETA ObtenerInformacionTarjeta(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ObtenerInformacionTarjeta", ReplyAction="http://tempuri.org/IEmisor/ObtenerInformacionTarjetaResponse")]
        System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.TARJETA> ObtenerInformacionTarjetaAsync(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ValidarTarjeta", ReplyAction="http://tempuri.org/IEmisor/ValidarTarjetaResponse")]
        string ValidarTarjeta(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/ValidarTarjeta", ReplyAction="http://tempuri.org/IEmisor/ValidarTarjetaResponse")]
        System.Threading.Tasks.Task<string> ValidarTarjetaAsync(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEmisor/GetDataUsingDataContractResponse")]
        AplicacionTarjetas.ServicioTarjetas.CompositeType GetDataUsingDataContract(AplicacionTarjetas.ServicioTarjetas.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmisor/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEmisor/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(AplicacionTarjetas.ServicioTarjetas.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmisorChannel : AplicacionTarjetas.ServicioTarjetas.IEmisor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmisorClient : System.ServiceModel.ClientBase<AplicacionTarjetas.ServicioTarjetas.IEmisor>, AplicacionTarjetas.ServicioTarjetas.IEmisor {
        
        public EmisorClient() {
        }
        
        public EmisorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmisorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmisorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmisorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AplicacionTarjetas.ServicioTarjetas.EMISOR[] ConsultarEmisor() {
            return base.Channel.ConsultarEmisor();
        }
        
        public System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.EMISOR[]> ConsultarEmisorAsync() {
            return base.Channel.ConsultarEmisorAsync();
        }
        
        public string ObtenerEmisorTarjeta(string numeroTarjeta) {
            return base.Channel.ObtenerEmisorTarjeta(numeroTarjeta);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEmisorTarjetaAsync(string numeroTarjeta) {
            return base.Channel.ObtenerEmisorTarjetaAsync(numeroTarjeta);
        }
        
        public AplicacionTarjetas.ServicioTarjetas.TARJETA ObtenerInformacionTarjeta(string numeroTarjeta) {
            return base.Channel.ObtenerInformacionTarjeta(numeroTarjeta);
        }
        
        public System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.TARJETA> ObtenerInformacionTarjetaAsync(string numeroTarjeta) {
            return base.Channel.ObtenerInformacionTarjetaAsync(numeroTarjeta);
        }
        
        public string ValidarTarjeta(string numeroTarjeta) {
            return base.Channel.ValidarTarjeta(numeroTarjeta);
        }
        
        public System.Threading.Tasks.Task<string> ValidarTarjetaAsync(string numeroTarjeta) {
            return base.Channel.ValidarTarjetaAsync(numeroTarjeta);
        }
        
        public AplicacionTarjetas.ServicioTarjetas.CompositeType GetDataUsingDataContract(AplicacionTarjetas.ServicioTarjetas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AplicacionTarjetas.ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(AplicacionTarjetas.ServicioTarjetas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
